[theme]
primaryColor = "#8000FF"  # צבע עיקרי (כמו כפתורים וקווים)
backgroundColor = "#fafbff"  # צבע רקע
secondaryBackgroundColor = "#E4E7EB"  # צבע רקע נוסף
textColor = "#343A40"  # צבע טקסט
font = "sans serif"  # גופן (Calibri, Arial וכו')
[client]
showSidebarNavigation = false
