[server]
port = 8000
enableCORS = false
headless = true

[theme]
primaryColor = "#8000FF"
backgroundColor = "#fafbff"
secondaryBackgroundColor = "#E4E7EB"
textColor = "#343A40"
font = "sans serif"

[client]
showSidebarNavigation = false